// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDxbzjlC0RzxJutdLHfOS-94V2SLUVtyY',
    appId: '1:481815235944:web:082cf2448c1d275a429add',
    messagingSenderId: '481815235944',
    projectId: 'booknex-partner',
    authDomain: 'booknex-partner.firebaseapp.com',
    storageBucket: 'booknex-partner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbMxMTZfH3jogf3qEZfTj5jpdoJkOsH9w',
    appId: '1:481815235944:android:03c2c5de9f0f8cef429add',
    messagingSenderId: '481815235944',
    projectId: 'booknex-partner',
    storageBucket: 'booknex-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPifjQOuxwmzoiW2iZr2UtYN6tCJGTLak',
    appId: '1:481815235944:ios:321069cf8034adea429add',
    messagingSenderId: '481815235944',
    projectId: 'booknex-partner',
    storageBucket: 'booknex-partner.firebasestorage.app',
    iosBundleId: 'com.example.booknexPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPifjQOuxwmzoiW2iZr2UtYN6tCJGTLak',
    appId: '1:481815235944:ios:321069cf8034adea429add',
    messagingSenderId: '481815235944',
    projectId: 'booknex-partner',
    storageBucket: 'booknex-partner.firebasestorage.app',
    iosBundleId: 'com.example.booknexPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDxbzjlC0RzxJutdLHfOS-94V2SLUVtyY',
    appId: '1:481815235944:web:694bd5b7e4fe386d429add',
    messagingSenderId: '481815235944',
    projectId: 'booknex-partner',
    authDomain: 'booknex-partner.firebaseapp.com',
    storageBucket: 'booknex-partner.firebasestorage.app',
  );
}
